---
title: "Final Project"
author: "Daniel Pinckney"
date: "12/3/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
Does the type of building affect the level of LEED certification it receives? In this study, I plan to examine the extent to which new buildings receive higher LEED certification levels. I hypothesize that new buildings receive higher LEED certification than retrofits of existing buildings. When building new buildings, contractors and architects have more freedom to design within the LEED framework and are able to satisfy more of the criteria for higher certification levels. When retrofitting existing structures, builders must work with the existing shell of the building, potentially limiting their ability to reach the highest levels of certification. If I observe higher certification levels with new builds relative to existing structures, this would provide support for my hypothesis. If, on the other hand, I observe lower or similar levels of certification with new builds, this would provide evidence against my hypothesis. When I run my regression of the LEED certification level on the building type indicator variable, a positive, significant coefficient would indicate support for my hypothesis.

## Data and Summarization
My sample is comprised of each of the LEED certified building projects in Montgomery County, Maryland from 2004 to 2015 excluding homes. My unit of analysis is a class of building (e.g., a new construction). The explanatory variable of interest is whether the construction is a new building or a retrofit of an existing structure. The variable is coded =1 for new construction or core & shell and =0 for existing buildings and commercial interiors. An interesting covariate is the year built, as new building practices may also improve scores. My outcome variable is the average LEED certification level the building type receives. The variable is coded from 1 to 4, where 1 is a platinum level certification and 4 is certified. This variable is measured from US Green Building Councils LEED ratings that evaluate various green building strategies across several categories. 
summary statistic - center & spread 
what does the dependent variable look like
factors or binary, include bar charts

## Results and Regression
regression table modelsummary

after this you only need your own interpretation
scatterplot main variable, dependent on y add trend line

## Conclusion