---
title: 'Final Project Milestone 2: Analyses'
author: "Daniel Pinckney"
date: "11/17/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
MoCo_MD_LEED_Cert <- read_csv("data/Montgomery_County_MD_LEED_Certified_Buildings.csv")
```

## Data Processing

#### Renaming the columns to make them workable

```{r}
colnames(MoCo_MD_LEED_Cert)
MoCo_MD_LEED_Cert <- MoCo_MD_LEED_Cert %>% 
  rename(
    name = "Building Name",
    path = "Path",
    cert_date = "Certification date",
    city = "City",
    state = "State",
    country = "Country",
    build_type = "Rating system",
    version = "Version",
    cert_name = "Certification level (name)",
    cert_num = "Certification level (numeric)"
  ) %>% 
  select(name, cert_date, build_type, cert_name, cert_num)
```

#### Making the independent variable

```{r}
MoCo_MD_LEED_Cert <- MoCo_MD_LEED_Cert %>% 
  mutate(new_build = case_when(
    build_type == "Commercial Interiors" ~ 0,
    build_type == "New Construction" ~ 1,
    build_type == "Core and Shell" ~ 1,
    build_type == "Schools - New Construction" ~ 1,
    build_type == "Existing Buildings" ~ 0,
    build_type == "Retail - New Construction" ~ 1,
    build_type == "Retail - Commercial Interiors" ~ 0
  )) %>% 
  drop_na(new_build)

summarize(MoCo_MD_LEED_Cert, 
          mean_new_build = mean(new_build))
```

#### Working with the Dependent Variable

```{r}
MoCo_MD_LEED_Cert %>% 
  group_by(new_build) %>% 
  summarize(
    mean_score = mean(cert_num)
  )

summarize(MoCo_MD_LEED_Cert, 
          mean_score = mean(cert_num))
```

#### Date

```{r}
MoCo_MD_LEED_Cert <- MoCo_MD_LEED_Cert %>% 
  mutate(cert_date = substr(cert_date, 7L, 10L)) %>% 
  mutate(cert_date = as.numeric(cert_date))
```


## Analysis

#### ATE Calculations

```{r}
MoCo_MD_LEED_Cert %>% 
  group_by(new_build) %>% 
  summarize(
    level_mean = mean(cert_num),
    level_se = sd(cert_num) / sqrt(n())
  ) %>% 
  pivot_wider(names_from = new_build, values_from = c(level_mean, level_se)) %>% 
  mutate(
    ate_level_diff = level_mean_1 - level_mean_0,
    ate_level_se = sqrt(level_se_1 ^ 2 + level_se_0 ^2)
  ) %>% 
  select(ate_level_diff, ate_level_se)
```

#### Plot

```{r}
ggplot(MoCo_MD_LEED_Cert, aes(cert_num)) +
  geom_histogram(fill = "seagreen", binwidth = 1, color = "black") +
  labs(y = "Number of Certified Buildings", x = "Certification Level",
       title = "Distribution of Building Certification Levels")
```


#### New Building Histogram

```{r}
MoCo_MD_LEED_Cert_new <- MoCo_MD_LEED_Cert %>% 
  filter(new_build == 1)

ggplot(MoCo_MD_LEED_Cert_new, aes(cert_num)) +
  geom_histogram(fill = "seagreen", binwidth = 1, color = "black") +
  labs(y = "Number of Certified Buildings", x = "Certification Level",
       title = "Distribution of New Building Certification Levels")
```


#### Existing Building Histogram

```{r}
MoCo_MD_LEED_Cert_exist <- MoCo_MD_LEED_Cert %>% 
  filter(new_build == 0)

ggplot(MoCo_MD_LEED_Cert_exist, aes(cert_num)) +
  geom_histogram(fill = "seagreen", binwidth = 1, color = "black") +
  labs(y = "Number of Certified Buildings", x = "Certification Level", 
       title = "Distribution of Existing Building Certification Levels")
```

#### Regression

```{r}
lin_fit <- lm(cert_num ~ new_build, data = MoCo_MD_LEED_Cert)
summary(lin_fit)

# I am not sure how to plot the regression for this data, but here it is

# also considering doing a regression like lm(cert_num ~ new_build + cert_date), 
# but the date data is strange
```

